no_balance_label = "GBP: No Update"
reset_label = "GBP: Reset"

[points]
"Balance/Rebalance" = -1
"Code Improvement" = 2
"Feature" = -1
"Fix" = 3
"Grammar and Formatting" = 1
"Performance" = 5
"Priority: CRITICAL" = 7
"Priority: High" = 6
"Quality of Life" = 1
"Refactor" = 4
"Sound" = -1
"Sprites" = -1
"Unit Tests" = 3
