no_balance_label = "GBP: No Update"
reset_label = "GBP: Reset"

[points]
"Balance/Rebalance" = -1
"Code Improvement" = 2
"Feature" = -1
"Fix" = 3
"Grammar and Formatting" = 1
"Performance" = 2
"Priority: CRITICAL" = 4
"Priority: High" = 3
"Quality of Life" = -1
"Refactor" = 2
"Sound" = -1
"Sprites" = -1
"Unit Tests" = 2
