language: generic
sudo: false
branches:
  except:
  - ___TGS3TempBranch
env:
    global:
    - BYOND_MAJOR="512"
    - BYOND_MINOR="1418"
    - NODE_VERSION="4"
    - RUST_G_VERSION="0.3.0"
matrix:
  - env:
    - BUILD_TOOLS=true
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - libssl-dev:i386
            - gcc-multilib
    cache:
      directories:
        - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
        - tgui/node_modules
        - $HOME/.rustup
        - $HOME/.cargo
  - env:
    - BUILD_TESTING=true
    - BUILD_TOOLS=false
    addons:
      apt:
        packages:
          - libc6-i386
          - libstdc++6:i386
    cache:
      directories:
        - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
  - env:
    - BUILD_TESTING=false
    - BUILD_TOOLS=false
    addons:
      mariadb: '10.2'
      apt:
        packages:
          - libc6-i386
          - libstdc++6:i386
    cache:
      directories:
        - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

install:
  - tools/travis/install_build_tools.sh
  - if [ !$BUILD_TOOLS ] && [ !$BUILD_TESTING ]; then mysql -u root -e 'CREATE DATABASE tg_travis;'; fi
  - if [ !$BUILD_TOOLS ] && [ !$BUILD_TESTING ]; then mysql -u root tg_travis < SQL/tgstation_schema.sql; fi

before_script:
  - tools/travis/before_build_tools.sh
  - tools/travis/before_build_byond.sh

script:
  - tools/travis/check_filedirs.sh tgstation.dme
  - tools/travis/build_tools.sh
  - tools/travis/build_dependencies.sh
  - tools/travis/build_byond.sh

