<<<<<<< HEAD
language: generic
=======
#pretending we're C because otherwise ruby/rvm will initialize, even with "language: dm".
language: c
>>>>>>> ccb55b121a3fd5338fc56a602424016009566488
sudo: false

env:
    global:
    - BYOND_MAJOR="510"
<<<<<<< HEAD
    - BYOND_MINOR="1332"
    - NODE_VERSION="4"
    - BUILD_TOOLS=false
    - DM_MAPFILE=""
    matrix:
    - BUILD_TOOLS=true
    - DM_MAPFILE="tgstation2"
    - DM_MAPFILE="metastation"
    - DM_MAPFILE="ministation"
    - DM_MAPFILE="dreamstation"
    - DM_MAPFILE="birdstation"
    - DM_MAPFILE="efficiencystation"
    - DM_MAPFILE="templates"


cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

=======
    - BYOND_MINOR="1345"
    matrix:
    - DM_MAPFILE="tgstation"
    - DM_MAPFILE="metaclub"
    - DM_MAPFILE="defficiency"
    - DM_MAPFILE="taxistation"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
    - $HOME/.cache/pip
>>>>>>> ccb55b121a3fd5338fc56a602424016009566488

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
<<<<<<< HEAD
      - python
      - python-pip

install:
  - tools/travis/install_build_tools.sh

before_script:
  - tools/travis/before_build_tools.sh
  - tools/travis/before_build_byond.sh

script:
  - tools/travis/check_filedirs.sh tgstation.dme
  - tools/travis/build_tools.sh
  - tools/travis/build_byond.sh
=======

install:
  - pip install --user PyYaml -q --download-cache $HOME/.pip-cache
  - pip install --user beautifulsoup4 -q --download-cache $HOME/.pip-cache

before_script:
  - chmod +x ./dm.sh
  - chmod +x ./install-byond.sh
  - ./install-byond.sh

script:
  - cat maps/*.* | awk '/step_x =/ && /step_y =/' | awk '!/step_y = 0/ || !/step_x = 0/ { exit 1 }'
  - python tools/ss13_genchangelog.py html/changelog.html html/changelogs --dry-run
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - ./dm.sh -M${DM_MAPFILE} vgstation13.dme

notifications:
  irc:
    channels:
      - "irc.rizon.net#vgstation"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
>>>>>>> ccb55b121a3fd5338fc56a602424016009566488
