language: generic
dist: xenial
sudo: false

branches:
  except:
  - ___TGS3TempBranch
  - ___TGSTempBranch

matrix:
  include:
    - name: "Run Linters"
      env: BUILT_TOOLS=true
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - python3-setuptools
      cache:
        directories:
          - tgui/node_modules
      install:
        - tools/travis/install_build_tools.sh
      before_script:
        - tools/travis/before_build_tools.sh
      script:
        - tools/travis/check_filedirs.sh tgstation.dme
        - tools/travis/build_tools.sh

    - name: "Compile All Maps"
      env: BUILD_TOOLS=false BUILD_TESTING=true
      addons:
        apt:
          packages:
            - libstdc++6:i386
      cache:
        directories:
          - $HOME/BYOND
      before_script:
        - tools/travis/before_build_byond.sh
        - tools/travis/build_byond.sh

    - name: "Compile and Run Tests"
      env: BUILD_TOOLS=false BUILD_TESTING=false
      addons:
        mariadb: '10.2'
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6:i386
            - libssl-dev:i386
            - gcc-multilib
            - g++-7
            - g++-7-multilib
            - libmariadb-client-lgpl-dev:i386
            - libmariadbd-dev
      cache:
        directories:
          - $HOME/.cargo
          - $HOME/BYOND
          - $HOME/MariaDB
          - $HOME/.rustup
      install:
        - mysql -u root -e 'CREATE DATABASE tg_travis;'
        - mysql -u root tg_travis < SQL/tgstation_schema.sql
        - mysql -u root -e 'CREATE DATABASE tg_travis_prefixed;'
        - mysql -u root tg_travis_prefixed < SQL/tgstation_schema_prefixed.sql
      before_script:
        - tools/travis/before_build_byond.sh
      script:
        - tools/travis/build_dependencies.sh || travis_terminate 1
        - tools/travis/build_byond.sh
