language: generic
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libmariadbclient-dev:i386

script:
  - ls /usr/include
  - ls /usr/lib/i386-linux-gnu
  - ls /usr/include/mysql

