version: '{build}'
skip_branch_with_pr: true
cache:
  - C:\byond\ -> tools/appveyor/build.ps1
build_script:
  - ps: tools/appveyor/build.ps1
  - tools/deploy.sh deploy
  - ps: "[System.IO.Compression.ZipFile]::CreateFromDirectory('deploy', 'deploy.zip')"
artifacts:
  - path: deploy.zip