version: '{build}'
skip_branch_with_pr: true
shallow_clone: true
cache:
  - C:\byond\ -> tools/appveyor/build.ps1
build_script:
  - ps: tools/appveyor/build.ps1
  - ps: "& tools/deploy.sh $env:APPVEYOR_BUILD_FOLDER + '/deploy'" 
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: "[System.IO.Compression.ZipFile]::CreateFromDirectory($env:APPVEYOR_BUILD_FOLDER + '/deploy', $env:APPVEYOR_BUILD_FOLDER + '/deploy.zip')"
artifacts:
  - path: deploy.zip
