# This configuration file forms the in-game chat filter.
# Values are stored as "word" = "reason for being banned".
# Values should be in lowercase to prevent errors down the line.
# Soft filter reasons should be kept short or the tgui gets messy

# Anything in here will be blocked from IC interactions, dead chat, and OOC
[shared]
"blockedinshared" = "This message is not allowed anywhere, please use a different weird test phrase."

# Anything in here is blocked just from IC interactions, such as chat or names, but is allowed in dead chat and OOC
[ic]
"blockedinic" = "This message is not allowed IC, please use a different weird test phrase."

# Anything in here is blocked from all IC interactions *except* PDAs.
# On /tg/, netspeak is OK in PDAs.
[ic_outside_pda]
"<(0_0<)" = "Kirby dancing is strictly prohibited on this server."

# Anything in here will warn the player if said in IC, Deadchat or OOC, the player must approve their message to send it
[soft_shared]
"softblocks" = "Insert reason here"

# InsertDescLater
[soft_ic]
"softerblocks" = "cat noises"

# InsertDescLater
[soft_ic_outside_pda]
"softestblocks" = "catter patter"
