directory = "_maps/RandomZLevels/modular_maps/caves/"

#Various bridges on the 2nd floor#
[rooms.caves_lvl2bridge1]
modules = ["caves_lvl2bridge1_broken.dmm", "caves_lvl2bridge1_unbroken.dmm"]

[rooms.caves_lvl2bridge2]
modules = ["caves_lvl2bridge2_broken.dmm", "caves_lvl2bridge2_unbroken.dmm"]

[rooms.caves_lvl2bridge3]
modules = ["caves_lvl2bridge3_broken.dmm", "caves_lvl2bridge3_unbroken.dmm"]

[rooms.caves_lvl2tunnelbridge]
modules = ["caves_lvl2tunnelbridge_broken.dmm", "caves_lvl2tunnelbridge_unbroken.dmm"]

#Randomly chosen combat segments on the 2nd floor#
#A - Destroyed ashwalker encampment
#B - Dead miner cave
#C - Small undead crypt
[rooms.caves_lvl2encounter1]
modules = ["caves_lvl2encounter1_a.dmm", "caves_lvl2encounter1_b.dmm", "caves_lvl2encounter1_c.dmm"]

#A - Timmy's lair
#B - Hidden away tendril
#C - Rift warp
[rooms.caves_lvl2encounter2]
modules = ["caves_lvl2encounter2_a.dmm", "caves_lvl2encounter2_b.dmm", "caves_lvl2encounter2_c.dmm"]

#A - Goliath pack
#B - Ashwalker outpost
#C - Elite goliath encounter
[rooms.caves_lvl2encounter3]
modules = ["caves_lvl2encounter3_a.dmm", "caves_lvl2encounter3_b.dmm", "caves_lvl2encounter3_c.dmm"]

#A - We're rich!
#B - Ashwalker bridge
#C - Destroyed ledge (blocked access)
[rooms.caves_lvl2encounter4]
modules = ["caves_lvl2encounter4_a.dmm", "caves_lvl2encounter4_b.dmm", "caves_lvl2encounter4_c.dmm"]

#Research outpost on the 2nd floor#
#All have similar loot apart from the loot in the site director's office, mostly just layout changes to keep it interesting
[rooms.caves_lvl2researchpost]
modules = ["caves_lvl2researchpost_a.dmm", "caves_lvl2researchpost_b.dmm", "caves_lvl2researchpost_c.dmm"]

#4th wall breaking room only occasionally accessible
#A - Mining centric
#B - Station centric
#C - Beach centric
[rooms.caves_lvl3tear]
modules = ["caves_lvl3tear_a.dmm", "caves_lvl3tear_b.dmm", "caves_lvl3tear_c.dmm"]

#1st segment of 3 on the 3rd floor
#A - Ashwalker village (stealth optional?)
#B - Mining strip with blocked passage that needs blown up
#C - Mining post with mass driver jumps - disabled atm need to do more testing on the jumps so they aren't bad
[rooms.caves_lvl3segment1]
modules = ["caves_lvl3segment1_a.dmm", "caves_lvl3segment1_b.dmm"]

#2nd segment of 3 on the 3rd floor
#A - Undead crypt
#B - Ayylmao zone - - disabled atm button being lame on toggle
#C - Research away mission but less bad
[rooms.caves_lvl3segment2]
modules = ["caves_lvl3segment2_a.dmm", "caves_lvl3segment2_c.dmm"]

#3rd segment of 3 on the 3rd floor
#A - Ant nest - disabled atm not done enough
#B - Bootleg hell zone
#C - Abandoned outpost - disabled atm not done enough
[rooms.caves_lvl3segment3]
modules = ["caves_lvl3segment3_b.dmm", "caves_lvl3segment3_b.dmm", "caves_lvl3segment3_b.dmm"]

#4th floor leading up to the boss arena
#A - Lava lake with several islands - disabled atm, needs redone
#B - Central cave with multiple tunnels
#C - Matrix zone (coders HATE ratvar) - disabled atm, sekrit 
[rooms.caves_lvl4]
modules = ["caves_lvl4_b.dmm", "caves_lvl4_b.dmm", "caves_lvl4_b.dmm"]

#4th floor boss arena
#A - idk yet lol
#B - idk yet lol
#C - idk yet lol
[rooms.caves_lvl4bossarena]
modules = ["caves_lvl4bossarena_a.dmm", "caves_lvl4bossarena_b.dmm", "caves_lvl4bossarena_c.dmm"]