directory = "_maps/shuttles/emergency_scrapheap/"

[rooms.shuttle]
modules = ["classic1.dmm"]

[rooms.classic_fore]
modules = ["classic_fore3.dmm"]

[rooms.classic_aft]
modules = ["classic_aft1.dmm"]
