directory = "_maps/map_files/tramstation/modular_pieces/"

[rooms.maintenance_upperdormsleft]
modules = ["maintenance_upperdormsleft_1.dmm", "maintenance_upperdormsleft_2.dmm"]

[rooms.maintenance_upperdormsleft_attachment]
modules = ["maintenance_upperdormsleft_attachment_1.dmm", "maintenance_upperdormsleft_attachment_2.dmm", "maintenance_upperdormsleft_attachment_3.dmm"]

[rooms.maintenance_upperdormsright]
modules = ["maintenance_upperdormsright_1.dmm", "maintenance_upperdormsright_2.dmm"]

[rooms.maintenance_upperdormsright_attachment]
modules = ["maintenance_upperdormsright_attachment_1.dmm", "maintenance_upperdormsright_attachment_2.dmm", "maintenance_upperdormsright_attachment_3.dmm"]

[rooms.maintenance_upperbridgeright]
modules = ["maintenance_upperbridgeright_1.dmm", "maintenance_upperbridgeright_2.dmm"]

[rooms.maintenance_upperbridgeright_attachment_a]
modules = ["maintenance_upperbridgeright_attachment_a_1.dmm", "maintenance_upperbridgeright_attachment_a_2.dmm, "maintenance_upperbridgeright_attachment_a_3.dmm"]

[rooms.maintenance_upperbridgeright_attachment_b]
modules = ["maintenance_upperbridgeright_attachment_b_1.dmm", "maintenance_upperbridgeright_attachment_b_2.dmm", "maintenance_upperbridgeright_attachment_b_3.dmm"]

[rooms.maintenance_upperbarright]
modules = ["maintenance_upperbarright_1.dmm", "maintenance_upperbarright_2.dmm"]

[rooms.maintenance_upperbarright_attachment_a]
modules = ["maintenance_upperbarright_attachment_a_1.dmm", "maintenance_upperbarright_attachment_a_2.dmm", "maintenance_upperbarright_attachment_a_3.dmm"]

[rooms.maintenance_upperbarright_attachment_b]
modules = ["maintenance_upperbarright_attachment_b_1.dmm", "maintenance_upperbarright_attachment_b_2.dmm", "maintenance_upperbarright_attachment_b_3.dmm"]