directory = "_maps/map_files/tramstation/maintenance_modules/"

[rooms.medsciupper]
modules = ["medsciupper_1.dmm", "medsciupper_2.dmm", "medsciupper_3.dmm"]

[rooms.medsciupper_attachment_a]
modules = ["medsciupper_attachment_a_1.dmm", "medsciupper_attachment_a_2.dmm", "medsciupper_attachment_a_3.dmm"]

[rooms.medsciupper_attachment_b]
modules = ["medsciupper_attachment_b_1.dmm", "medsciupper_attachment_b_2.dmm", "medsciupper_attachment_b_3.dmm"]

[rooms.barcargoupper]
modules = ["barcargoupper_1.dmm", "barcargoupper_2.dmm", "barcargoupper_3.dmm"]

[rooms.barcargoupper_attachment_a]
modules = ["barcargoupper_attachment_a_1.dmm", "barcargoupper_attachment_a_2.dmm", "barcargoupper_attachment_a_3.dmm"]

[rooms.barcargoupper_attachment_b]
modules = ["barcargoupper_attachment_b_1.dmm", "barcargoupper_attachment_b_2.dmm", "barcargoupper_attachment_b_3.dmm"]
