directory = "_maps/modular_generic/"

[rooms.station_small]
modules = ["station_small_1.dmm"]

[rooms.station_medium]
modules = ["station_medium_1.dmm", "station_medium_2.dmm", "station_medium_3.dmm", "station_medium_4.dmm", "station_medium_5.dmm", "station_medium_6.dmm", "station_medium_7.dmm", "station_medium_8.dmm"]

[rooms.station_large]
modules = ["station_large_1.dmm", "station_large_2.dmm", "station_large_3.dmm", "station_large_4.dmm"]

[rooms.beach_small]
modules = []

[rooms.beach_medium]
modules = ["beach_medium_1.dmm", "beach_medium_2.dmm"]

[rooms.beach_large]
modules = ["beach_large_1.dmm"]

[rooms.jungle_small]
modules = []

[rooms.jungle_medium]
modules = ["jungle_medium_1.dmm"]

[rooms.jungle_large]
modules = ["jungle_large_1.dmm"]

[rooms.ice_small]
modules = ["ice_small_1.dmm"]

[rooms.ice_medium]
modules = ["ice_medium_1.dmm"]

[rooms.ice_large]
modules = ["ice_large_1.dmm"]
