directory = "_maps/modular_generic"

[rooms.station_small]
modules = []

[rooms.station_medium]
modules = ["station_medium_1", "station_medium_2", "station_medium_3", "station_medium_4", "station_medium_5", "station_medium_6", "station_medium_7"]

[rooms.station_large]
modules = ["station_large_1", "station_large_2", "station_large_3", "station_large_4"]


[rooms.beach_small]
modules = []

[rooms.beach_medium]
modules = ["beach_medium_1"]

[rooms.beach_large]
modules = ["beach_large_1"]


[rooms.jungle_small]
modules = []

[rooms.jungle_medium]
modules = ["jungle_medium_1"]

[rooms.jungle_large]
modules = ["jungle_large_1"]


[rooms.ice_small]
modules = []

[rooms.ice_medium]
modules = ["ice_medium_1"]

[rooms.ice_large]
modules = ["ice_large_1"]
