rules:
  # radar/cognitive-complexity: warn
  radar/max-switch-cases: warn
  radar/no-all-duplicated-branches: warn
  radar/no-collapsible-if: warn
  radar/no-collection-size-mischeck: warn
  radar/no-duplicate-string: warn
  radar/no-duplicated-branches: warn
  radar/no-element-overwrite: warn
  radar/no-extra-arguments: warn
  radar/no-identical-conditions: warn
  radar/no-identical-expressions: warn
  radar/no-identical-functions: warn
  radar/no-inverted-boolean-check: warn
  radar/no-one-iteration-loop: warn
  radar/no-redundant-boolean: warn
  radar/no-redundant-jump: warn
  radar/no-same-line-conditional: warn
  radar/no-small-switch: warn
  radar/no-unused-collection: warn
  radar/no-use-of-empty-return-value: warn
  radar/no-useless-catch: warn
  radar/prefer-immediate-return: warn
  radar/prefer-object-literal: warn
  radar/prefer-single-boolean-return: warn
  radar/prefer-while: warn
