enableScripts: false

logFilters:
  ## DISABLED_BUILD_SCRIPTS
  - code: YN0004
    level: discard
  ## FETCH_NOT_CACHED
  ## Too many cache misses on first install.
  - code: YN0013
    level: discard
  ## INCOMPATIBLE_OS
  ## fsevents are not supposed to build, they're macOS specific.
  - code: YN0062
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
