mode = "BitmaskSlice"

produce_dirs = false
smooth_diagonally = false

[icon_size]
x = 32
y = 32

[output_icon_pos]
x = 0
y = 0

[output_icon_size]
x = 32
y = 32

[positions]
convex = 0
horizontal = 1
vertical = 2
concave = 3

[cut_pos]
x = 16
y = 16
