services:
  tts:
    container_name: tts

    build: ./tts
    ports:
      - "5002:5002"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:5002/health-check"]
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 30s
    links:
      - "ffmpeg:ffmpeg-container"
  ffmpeg:
    container_name: ffmpeg

    build: ./ffmpeg
    ports:
      - "5003:5003"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:5003/health-check"]
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 30s
