name: CI Suite
on:
  push:
    branches:
    - master
    - 'project/**'
    - 'gh-readonly-queue/master/**'
    - 'gh-readonly-queue/project/**'
  pull_request:
    branches:
    - master
    - 'project/**'
  merge_group:
    branches:
    - master
jobs:
  mothblocks:
    name: Mothblocks Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y gcc-multilib g++-multilib
      - run: g++ -nostdlib -m32 -shared -fPIC -o libbyond_sleeping_procs_ci.so main.cpp
      - uses: actions/upload-artifact@v3
        with:
          name: libbyond_sleeping_procs_ci
          path: libbyond_sleeping_procs_ci.so
