name: CI Suite
on:
  push:
    branches:
    - master
    - 'project/**'
    - 'gh-readonly-queue/master/**'
    - 'gh-readonly-queue/project/**'
  pull_request:
    branches:
    - master
    - 'project/**'
  merge_group:
    branches:
    - master
jobs:
  mothblocks:
    name: Mothblocks Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ldd ./libbyond_sleeping_procs.so
