#Example worflow for Gamer025/CodeOwnersParser

name: Codeowner Assignment

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

jobs:
  assign-users:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      - name: CodeOwnersParser
        id: CodeOwnersParser
        uses: tgstation/CodeOwnersParser@v1

      #Assign users
      - name: Assign users
        if: steps.CodeOwnersParser.outputs.owners != ''
        uses: tgstation/AssignUser@v1
        with:
          separator: ' '
          users: ${{ steps.CodeOwnersParser.outputs.owners }}
