name: Auto Label

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write # to apply labels
  issues: write # to apply labels

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Auto Labeler
      uses: actions/github-script@v7
      with:
        script: |
          const { get_updated_label_set } = await import('${{ github.workspace }}/tools/pull_request_hooks/autoLabel.js');
          const new_labels = await get_updated_label_set({ github, context });
          github.rest.issues.setLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: new_labels,
          });
          console.log(`Labels updated: ${new_labels}`);
        github-token: ${{ steps.app-token-generation.outputs.token || secrets.GITHUB_TOKEN }}
