name: PR title emoji
on:
  pull_request:
    types: [opened, edited]

jobs:
  stripper:
    runs-on: ubuntu-20.04
    steps:
    - uses: Wayland-Smithy/emoji-stripper-action@9c788a6f42dddb57482770cb2ba4858a9b8fa84e
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
