name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: "This PR has been inactive for 7 days with no maintainer action, and has been automatically marked as Blocked. This means maintainers are not interested in your pull request, outstanding review comments are still unaddressed, maintainers are actively opposing your pull request, or discussion is still ongoing about your pull request. Please reach out to the maintainers for clarification if you believe none of these are the case. If the Blocked tag is not removed in 7 days, the pull request will automatically close."
        days-before-stale: 7
        days-before-close: 7
        stale-pr-label: 'Blocked'
        days-before-issue-stale: -1
        stale-issue-label: 'Cleanup Flagged'
        remove-issue-stale-when-updated: false
        exempt-pr-labels: 'RED LABEL,Good First PR'
        operations-per-run: 300
