name: Test Merge Detector
on:
  schedule:
  - cron: "*/30 * * * *"
  workflow_dispatch:
jobs:
  test_merge_bot:
      name: Test Merge Detector
      runs-on: ubuntu-20.04
      steps:
        - name: Check for ACTIONS_ENABLED
          id: secrets_set
          env:
            ENABLER_SECRET: ${{ secrets.ACTIONS_ENABLED }}
          run: |
            unset SECRET_EXISTS
            if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
            echo "::set-output name=ACTIONS_ENABLED::$SECRET_EXISTS"
        - name: Checkout
          if: steps.secrets_set.outputs.ACTIONS_ENABLED
          uses: actions/checkout@v3
        - name: Prepare module
          if: steps.secrets_set.outputs.ACTIONS_ENABLED
          run: |
            # This is needed because node-fetch needs import and doesn't work with require :/
            echo "{\"type\": \"module\"}" > package.json
            npm install node-fetch
        - name: Check for test merges
          if: steps.secrets_set.outputs.ACTIONS_ENABLED
          uses: actions/github-script@v6
          with:
            script: |
              const { processTestMerges } = await import('${{ github.workspace }}/tools/test_merge_bot/main.js')
              await processTestMerges({ github, context })
