name: Test Merge Detector
on:
  push:
    branches:
    - tm-bot
  # MOTHBLOCKS TODO: cron
  workflow_dispatch:
jobs:
  test_merge_bot:
      name: Check for ACTION_ENABLER secret and pass true to output if it exists to be checked by later steps
      runs-on: ubuntu-20.04
      steps:
        - name: Cheeck for ACTION_ENABLER
          id: secrets_set
          env:
            ENABLER_SECRET: ${{ secrets.ACTION_ENABLER }}
          run: |
            unset SECRET_EXISTS
            if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
            echo "::set-output name=ACTIONS_ENABLED::$SECRET_EXISTS"
        - name: Checkout
          if: steps.secrets_set.outputs.ACTIONS_ENABLED
          uses: actions/checkout@v3
          with:
            ref: "tm-bot" # MOTHBLOCKS TODO: Remove
        - name: Check for test merges
          if: steps.secrets_set.outputs.ACTIONS_ENABLED
          uses: actions/github-script@v6
          with:
            script: |
              const { processTestMerges } = await import('${{ github.workspace }}/tools/test_merge_bot/main.js')
              await processTestMerges({ github, context })
