name: Wallening Revert

on:
  pull_request:
    types:
      - closed
    branches:
      - 1989-11-09

jobs:
  generate-master-pr:
    name: Move Process Along
    runs-on: ubuntu-latest
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          dotnet-quality: ga

      - name: Generate App Token
        id: app-token-generation
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 1989-11-09
          fetch-depth: 610
          token: ${{ steps.app-token-generation.outputs.token }}

      - name: Build Helper
        run: dotnet publish tools/Tgstation.WalleningRevertHelper/Tgstation.WalleningRevertHelper.csproj -c Release -o wallening_helper

      - name: Run Helper (Init)
        if: ${{ vars.WALLENING_REVERT_PR == '' }}
        id: helper-init
        run: dotnet wallening_helper/Tgstation.WalleningRevertHelper.dll init ${{ steps.app-token-generation.outputs.token }}

      - name: Run Helper (Next)
        if: ${{ vars.WALLENING_REVERT_PR != '' }}
        id: helper-next
        run: dotnet wallening_helper/Tgstation.WalleningRevertHelper.dll next ${{ steps.app-token-generation.outputs.token }} ${{ github.event.pull_request.number }} ${{ vars.WALLENING_REVERT_PR }}

      - name: Enable Automerge (Init)
        if: ${{ steps.helper-init.outputs.nextpr != '' && vars.WALLENING_REVERT_PR == '' }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.app-token-generation.outputs.token }}
          pull-request-number: ${{ steps.helper-init.outputs.nextpr }}
          merge-method: squash

      - name: Enable Automerge (Next)
        if: ${{ steps.helper-next.outputs.nextpr != '' && vars.WALLENING_REVERT_PR != '' }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.app-token-generation.outputs.token }}
          pull-request-number: ${{ steps.helper-next.outputs.nextpr }}
          merge-method: squash
